local:
  project: mold 
  version: v1.0.0
  runtime:
    debug: True
  security:
    authentication:
      secretkey: xxx
      jwtissuer: idpdecathlon.preprod.org
      jwtexpirehour: 24
      jwtheaderprefix: Mold
    cors:
      alloworigins: ["http://127.0.0.1:8083", "http://localhost:8083", "https://assetppd.decathlon.net"]
      allowmethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      allowheaders: ["Origin", "Content-Length", "Content-Type", "authorization"]
      ExposeHeaders: ["Content-Length"]
      allowcredentials: True
      maxagehour: 12
  webapp:
    port: 9000
    readtimeoutsecond: 30
    readheadertimeoutsecond: 30
    writertimeoutsecond: 30
    idletimeoutsecond: 30
    maxheaderbytes: 1048576
    templatepath: templates/*
    mediaurl: /api/media
    mediapath: ./media
    staticurl: /api/static
    staticpath: ./static
    pagesize: 20
    maxbodysize: 5242880
  log:
    ginmode: release
    logrootpath: /var/log/mold_api
    logname: app.log
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      maxidle: 30
      maxactive: 30
      idletimeout: 200
    gcache:
      cachesize: 50
      timeout: 30
  database:
    type: postgres
    name: trinity
    user: trinity
    password: 123456
    host: 127.0.0.1
    port: 60901
    option: sslmode=disable #mysql option: charset=utf8&parseTime=True&loc=Local
    tableprefix: trinity_
    dbmaxidleconn: 10
    dbmaxopenconn: 100
preprod:
  project: mold 
  version: v1.0.0
  runtime:
    debug: True
  security:
    authentication:
      secretkey: xxx
      jwtissuer: idpdecathlon.preprod.org
      jwtexpirehour: 24
      jwtheaderprefix: Mold
    cors:
      alloworigins: ["http://127.0.0.1:8083", "http://localhost:8083", "https://assetppd.decathlon.net"]
      allowmethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      allowheaders: ["Origin", "Content-Length", "Content-Type", "authorization"]
      ExposeHeaders: ["Content-Length"]
      allowcredentials: True
      maxagehour: 12
  webapp:
    port: 9000
    readtimeoutsecond: 30
    readheadertimeoutsecond: 30
    writertimeoutsecond: 30
    idletimeoutsecond: 30
    maxheaderbytes: 1048576
    templatepath: templates/*
    mediaurl: /api/media
    mediapath: ./media
    staticurl: /api/static
    staticpath: ./static
    pagesize: 20
    maxbodysize: 5242880
  log:
    ginmode: debug
    logrootpath: /var/log/mold_api
    logname: app.log
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      maxidle: 30
      maxactive: 30
      idletimeout: 200
    gcache:
      cachesize: 50
      timeout: 30
  database:
    type: postgres
    name: mold
    user: mold
    password: 123456
    host: 127.0.0.1
    port: 60901
    option: sslmode=disable #mysql option: charset=utf8&parseTime=True&loc=Local
    tableprefix: mold_
    dbmaxidleconn: 10
    dbmaxopenconn: 100