local:
  project: trinity 
  tags: ["primary","v1"]
  version: v1.0.0
  runtime:
    debug: True
  security:
    authentication:
      secretkey: xxx
      jwtissuer: isser
      jwtexpirehour: 24
      jwtheaderprefix: Bearer
      jwtverifyissuer: False
      jwtverifyexpirehour: False
    cors:
      enable: True
      alloworigins: []
      allowmethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      allowheaders: ["Origin", "Content-Length", "Content-Type", "authorization", "x-api-key"]
      ExposeHeaders: ["Content-Length"]
      allowcredentials: True
      maxagehour: 12
    tls:
      ca_pem_file: /Users/daniel/Documents/workspace/SolutionDelivery/conf/ca.pem
      server_pem_file: /Users/daniel/Documents/workspace/SolutionDelivery/conf/server/server.pem
      server_key_file: /Users/daniel/Documents/workspace/SolutionDelivery/conf/server/server.key
      client_pem_file: xx
      client_key_file: xx
  webapp:
    type: HTTP
    address: 127.0.0.1
    port: 9000
    readtimeoutsecond: 30
    readheadertimeoutsecond: 30
    writertimeoutsecond: 30
    idletimeoutsecond: 30
    maxheaderbytes: 1048576
    templatepath: templates/*
    mediaurl: /api/media
    mediapath: ./media
    staticurl: /api/static
    staticpath: ./static
    migrationpath: ./static/migrations
    pagesize: 20
    maxbodysize: 5242880
    atomicrequest: true
    baseurl: /trinitygo
  log:
    logrootpath: /var/log/trinity
    logname: app.log
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      maxidle: 30
      maxactive: 30
      idletimeout: 200
    gcache:
      cachesize: 50
      timeout: 24
  database:
    type: postgres
    name: trinity
    user: trinity
    password: 123456
    host: 127.0.0.1
    port: 60901
    option: sslmode=disable #mysql option: charset=utf8&parseTime=True&loc=Local
    tableprefix: trinity_
    dbmaxidleconn: 10
    dbmaxopenconn: 100
  servicemesh:
    address: 127.0.0.1
    port: 8500
    deregister_after_critical: 60
    health_check_interval: 10
    auto_register: False
develop:
  project: trinity 
  version: v1.0.0
  runtime:
    debug: True
  security:
    authentication:
      secretkey: xxx
      jwtissuer: isser
      jwtexpirehour: 24
      jwtheaderprefix: Bearer
      jwtverifyissuer: False
      jwtverifyexpirehour: False
    cors:
      enable: True
      alloworigins: []
      allowmethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      allowheaders: ["Origin", "Content-Length", "Content-Type", "authorization", "x-api-key"]
      ExposeHeaders: ["Content-Length"]
      allowcredentials: True
      maxagehour: 12
  webapp:
    port: 8001
    readtimeoutsecond: 30
    readheadertimeoutsecond: 30
    writertimeoutsecond: 30
    idletimeoutsecond: 30
    maxheaderbytes: 1048576
    templatepath: templates/*
    mediaurl: /api/media
    mediapath: ./media
    staticurl: /api/static
    staticpath: ./static
    migrationpath: ./static/migrations
    pagesize: 20
    maxbodysize: 5242880
    atomicrequest: true
    baseurl: /trinitygo
  log:
    logrootpath: /var/log/trinity
    logname: app.log
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      maxidle: 30
      maxactive: 30
      idletimeout: 200
    gcache:
      cachesize: 50
      timeout: 30
  database:
    type: postgres
    name: trinity
    user: trinity
    password: 123456
    host: 10.0.0.52
    port: 60901
    option: sslmode=disable #mysql option: charset=utf8&parseTime=True&loc=Local
    tableprefix: trinity_
    dbmaxidleconn: 10
    dbmaxopenconn: 100
preprod:
  project: trinity 
  version: v1.0.0
  runtime:
    debug: True
  security:
    authentication:
      secretkey: xxx
      jwtissuer: isser
      jwtexpirehour: 24
      jwtheaderprefix: Bearer
      jwtverifyissuer: False
      jwtverifyexpirehour: False
    cors:
      enable: True
      alloworigins: []
      allowmethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      allowheaders: ["Origin", "Content-Length", "Content-Type", "authorization"]
      ExposeHeaders: ["Content-Length"]
      allowcredentials: True
      maxagehour: 12
  webapp:
    port: 3000
    readtimeoutsecond: 30
    readheadertimeoutsecond: 30
    writertimeoutsecond: 30
    idletimeoutsecond: 30
    maxheaderbytes: 1048576
    templatepath: templates/*
    mediaurl: /api/media
    mediapath: ./media
    staticurl: /api/static
    staticpath: ./static
    migrationpath: ./static/migrations
    pagesize: 20
    maxbodysize: 5242880
    atomicrequest: true
    baseurl: /trinitygo
  log:
    logrootpath: /var/log/trinity
    logname: app.log
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      maxidle: 30
      maxactive: 30
      idletimeout: 200
    gcache:
      cachesize: 50
      timeout: 30
  database:
    type: postgres
    name: trinity
    user: trinity
    password: trinity123666
    host: 10.71.160.60
    port: 60901
    option: sslmode=disable #mysql option: charset=utf8&parseTime=True&loc=Local
    tableprefix: trinity_
    dbmaxidleconn: 10
    dbmaxopenconn: 100
master:
  project: trinity 
  version: v1.0.0
  runtime:
    debug: True
  security:
    authentication:
      secretkey: xxx
      jwtissuer: idpdecathlon.preprod.org
      jwtexpirehour: 24
      jwtheaderprefix: Bearer
      jwtverifyissuer: False
      jwtverifyexpirehour: False
    cors:
      enable: True
      alloworigins: []
      allowmethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      allowheaders: ["Origin", "Content-Length", "Content-Type", "authorization"]
      ExposeHeaders: ["Content-Length"]
      allowcredentials: True
      maxagehour: 12
  webapp:
    port: 3000
    readtimeoutsecond: 30
    readheadertimeoutsecond: 30
    writertimeoutsecond: 30
    idletimeoutsecond: 30
    maxheaderbytes: 1048576
    templatepath: templates/*
    mediaurl: /api/media
    mediapath: ./media
    staticurl: /api/static
    staticpath: ./static
    migrationpath: ./static/migrations
    pagesize: 20
    maxbodysize: 5242880
    atomicrequest: true
    baseurl: /trinitygo
  log:
    logrootpath: /var/log/trinity_api
    logname: app.log
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      maxidle: 30
      maxactive: 30
      idletimeout: 200
    gcache:
      cachesize: 50
      timeout: 30
  database:
    type: postgres
    name: trinity
    user: trinity
    password: trinity123666
    host: 10.71.160.60
    port: 60901
    option: sslmode=disable #mysql option: charset=utf8&parseTime=True&loc=Local
    tableprefix: trinity_
    dbmaxidleconn: 10
    dbmaxopenconn: 100